# Ключевые слова для быстрой проверки, сгруппированные по интентам.

# Интент: Запись на пробный урок
booking_request:
  keywords:
    - "записаться на урок"
    - "хочу на пробное"
    - "запиши на пробное"
    - "записать ребенка"
    - "забронировать время"
    - "есть свободные слоты"
    - "как записаться"
    - "хочу записаться"
    - "да, хочу на пробный урок"
    - "записаться"
    - "на пробник"
    - "хочу попробовать"
    - "давайте начнем"

# Интент: Отмена записи
cancellation:
  keywords:
    - "отменить"
    - "отменить занятие"
    - "отмени"
    - "я хочу отказаться"
    - "отмена"
    - "отказ"
    - "не придём"
    - "не сможем прийти"
    - "не сможем придти"
    - "нас не будет"
    - "мы передумали"
    - "снимите бронь"

# Интент: Перенос записи
reschedule:
  keywords:
    - "перенести"
    - "перенести занятие"
    - "перезаписаться на другое время"
    - "поменять время урока"
    - "изменить запись"
    - "перенос"
    - "поменять"

# Интент: Проверка статуса записи
check_booking:
  keywords:
    - "проверить запись"
    - "посмотреть мои занятия"
    - "на какое время я записан"
    - "какие у меня уроки"
    - "напомни про запись"
    - "когда у нас урок"
    - "подтвердите запись"

# Интент: Запрос цены
price_request:
  keywords:
    - "сколько стоит"
    - "какая цена"
    - "стоимость"
    - "цены"
    - "прайс"
    - "как оплатить"
    - "как оплатить курс"
    - "как происходит оплата"
    - "способ оплаты"
    - "как платить"
    - "оплата курса"
    - "как заплатить"
  callback_keys:
    - "price_request"
    - "template_faq_payment"

# Интент: Вопросы о содержании курса
course_details:
  keywords:
    - "что будут делать"
    - "что входит в курс"
    - "программа курса"
    - "какие темы изучают"
    - "расскажите о курсе"
  callback_keys:
    - "course_details"
    - "faq:courses" 

# Интент: В чем разница между курсами
course_difference:
  keywords:
    - "в чем разница"
    - "отличия курсов"
    - "какой курс лучше"
  callback_keys:
    - "course_difference"

# Интент: Уточнение про льготы
social_status_info:
  keywords:
    - "я многодетная мама"
    - "я многодетный отец"
    - "у меня много детей"
    - "мы многодетные"
    - "для многодетных"
    - "одинокий родитель"
    - "мать-одиночка"
    - "отец-одиночка"
    - "какая у вас скидка"
    
# Интент: Вопрос об индивидуальности занятий
# Интент: Индивидуальные занятия
individual_lessons:
  keywords:
    - "индивидуальные занятия"
    - "уроки один на один"
    - "занятия с преподавателем лично"
    - "сколько стоит индивидуальный урок"
    - "цена индивидуальных уроков"
    - "как записаться на индивидуальное занятие"
    - "индивидуальный формат"
    - "урок персонально"
    - "индивидуальная программа"
  callback_keys:
    - "individual_lessons"

# Интент: Приветствие
greeting:
  keywords:
    - "привет"
    - "добрый день"
    - "здравствуйте"

# Интент: Просьба позвать человека
human_operator:
  keywords:
    - "позвать оператора"
    - "поговорить с человеком"
    - "нужен менеджер"
    - "позвать менеджера"
    - "позови менеджера"
    - "хочу поговорить с менеджером"
    - "соедини с менеджером"

about_school_name:
  keywords:
    - "почему школа так называется"
    - "почему no bugs"
    - "что значит no bugs"
    - "смысл названия"
    - "называется no"
    - "про название"
    - "название школы"
    - "откуда название"
    - "почему нет багов"

  # Этот интент не требует семантического поиска, так как ключевые слова очень специфичны
  semantic_search: false

trial_lesson_faq:
  keywords: 
    - "как проходит пробный урок"
    - "что на пробном уроке"
    - "как проходит пробный"
    - "что будет на пробном"
    - "расскажите про пробный"
    - "про пробный урок"
    - "что делаем на пробном"
    - "сколько длится пробный"
    - "длительность пробного"
    - "формат пробного урока"       # можно оставить пустым, это чисто "переход" по колбэку
  callback_keys:
    - "faq_trial_lesson"

# Интент: Информация о боте
about_bot:
  keywords:
    - "о боте"
    - "кто ты"
    - "расскажи о себе"
    - "что ты умеешь"
    - "твои функции"
    - "кто тебя создал"
  callback_keys:
    - "about_bot"

